name: Deploy to Kubernetes (Docker Desktop)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      - name: Set up Kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl config use-context docker-desktop

      - name: Debug Kubectl Configuration
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config || echo "Decoding failed!"
          ls -la $HOME/.kube || echo "Kube directory missing!"
          cat $HOME/.kube/config || echo "Kube config file missing!"
          kubectl config view || echo "Kubectl config not found!"

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-manifest.yaml
          kubectl rollout status deployment myapp

      - name: Verify Deployment
        run: kubectl get pods,svc
